### ISSUE TITLE
have typescript installed?

### ISSUE THREAD

**Issue by uptownhr** [chanlito/nuxt-ts-module#2]
I think it might be a good idea to include typescript as a dep in the module. People looking at using modules will most likely want to just install the module. Are there are some other issues with doing that?

**Comment by chanlito** [comment]
@uptownhr I think so some people, might want to use different version of typescript.

**Comment by uptownhr** [comment]
I agree but as a module for typescript, IMO the aim should be to work on the latest TS. I think along the lines of Nuxt trying to be inline with the latest view or other nuxt-modules like axios to be up to date with the latest axios. It would be weird if nuxt asks you to install your own vue or if the axios-module asks to install your axios version. 

I understand people want flexibility but the populous i believe want something thatt just works off the bat on the latest version. A guide on using yarn/npm to resolve different version can be made for flexibility purposes
